import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/d0d3619a1c.js" crossOrigin="anonymous" defer></script>
      </head>
      <body
        className={`${geistSans.variable} bg-gray-100`}
      >

        <Header />
        <main className="main-container">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
